### PR TITLE
Add support for other architectures

### PR DESCRIPTION
**Pull request by janvrany**
This PR contains changes / cleanups I did in order to add (some) RISC-V support. 
RISC-V codegen is not part of this PR, this will come later (have to tie some loose ends
in ArchC and I do not want to hold this longer, especially when new code seems to be
landing soon)

### CODE REVIEW

**Comment by janvrany** [comment]
Okay. I'll give it one more week and if there are no more comments, I'll merge it :-)

**Comment by melkyades** [comment]
Please don't merge. The work on late binding of identifiers led to a huge refactoring / minimization of powerlang that is still wip. Merging this branch would only add a git conflict soon as nativization code is being moved out to some other repository. We will need to schedule a hangout to sort out this.

**Comment by janvrany** [comment]
OK, will hold it for a bit.

**Comment by janvrany** [comment]
Closing, see https://github.com/powerlang/powerlang/pull/66#issuecomment-1120045454 :

> But #65 won't go into this repo anyway

**Comment by melkyades** [comment]
The code of this branch was finally ported to bee-dmr repo. It still does not work, as modules don't work yet (among others), and not even in master yet. There were some extra renames (https://github.com/powerlang/powerlang/tree/jp/wip/support-other-achs-with-extras). See commit https://github.com/powerlang/bee-dmr/commit/459e362e1de5f4fe5b5c1d8e3fefd61632caddd4

**Pull request closed without merging**
